### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jwo** [scottburton11/Shopping-Ember.js#1]
Thinking we could add some instructions to the README to get started.. I attempted, but had a couple of stumbling blocks.
1. Is it right that I should be running the gilt server on port 9292 before running this?
2. Is there a local database for this project in use?

More questions on the gilt, but want to make sure it's right to have that running vs something else.

**Comment by scottburton11** [comment]
That's right; use [gilt_api](https://github.com/scottburton11/gilt_api) as a backend; run `rackup` to start it. I created the API separately so that I could use the same one with all three example projects.

There's no database needed for this app.

I'll update the README, and the one for gilt_api as well.

**Comment by scottburton11** [comment]
Alright @jwo all fixed up. See if you can get started with those instructions.

Mind you, a few features just don't work at all, Ember-wise. Post any Issues you encounter, and we'll try to get them fixed up.

**Comment by jwo** [comment]
This worked for me, btw --- only thing I didn't figure out was how to make the images appear, but that wasn't all that important to me.. just wanted to see the three frameworks work (accomplished).

**Comment by scottburton11** [comment]
run `rake products:download_images` on gilt_api, then `cp -R lib/public/images/share ../Shopping-Ember.js/public/images` and you're off and running.
